export default {
    archetopics: [
        { name: 'Addiction', imagePath: '/images/archetopics/Addiction.png' },
        { name: 'Art', imagePath: '/images/archetopics/art.png' },
        { name: 'Attention', imagePath: '/images/archetopics/Attention.png' },
        { name: 'Beauty', imagePath: '/images/archetopics/Beauty.png' },
        { name: 'Beginning', imagePath: '/images/archetopics/Beginning.png' },
        { name: 'Birth', imagePath: '/images/archetopics/Birth.png' },
        { name: 'Cosmos', imagePath: '/images/archetopics/Cosmos.png' },
        { name: 'Death', imagePath: '/images/archetopics/Death.png' },
        { name: 'Ego', imagePath: '/images/archetopics/Ego.png' },
        { name: 'Empathy', imagePath: '/images/archetopics/Empathy.png' },
        { name: 'End', imagePath: '/images/archetopics/End.png' },
        { name: 'Eutopia', imagePath: '/images/archetopics/Eutopia.png' },
        { name: 'Future', imagePath: '/images/archetopics/Future.png' },
        { name: 'Game', imagePath: '/images/archetopics/Game.png' },
        { name: 'Gift', imagePath: '/images/archetopics/Gift.png' },
        { name: 'History', imagePath: '/images/archetopics/History.png' },
        { name: 'Human', imagePath: '/images/archetopics/Human.png' },
        { name: 'Life', imagePath: '/images/archetopics/Life.png' },
        { name: 'Paradox', imagePath: '/images/archetopics/Paradox.png' },
        { name: 'Shadow', imagePath: '/images/archetopics/art.png' },
        { name: 'Society', imagePath: '/images/archetopics/art.png' },
        { name: 'Time', imagePath: '/images/archetopics/art.png' },
        { name: 'Truth', imagePath: '/images/archetopics/art.png' },
    ],
    liminal: [
        { name: 'Authentic Relating', imagePath: '/images/liminal/authentic-relating.png' },
        {
            name: 'Collaborative Governance',
            imagePath: '/images/liminal/collaborative-governance.png',
        },
        { name: 'Community Building', imagePath: '/images/liminal/community-building.png' },
        { name: 'Embodiment', imagePath: '/images/liminal/embodiment.png' },
        { name: 'Emergence', imagePath: '/images/liminal/emergence.png' },
        { name: 'Existential Risk', imagePath: '/images/liminal/existential-risk.png' },
        { name: 'The Infinite Game', imagePath: '/images/liminal/the-infinite-game.png' },
        { name: 'Integral Theory', imagePath: '/images/liminal/integral-theory.png' },
        { name: 'Meditation', imagePath: '/images/liminal/meditation.png' },
        { name: 'Metacrisis', imagePath: '/images/liminal/metacrisis.png' },
        { name: 'Metamodernism', imagePath: '/images/liminal/metamodernism.png' },
        { name: 'Permaculture', imagePath: '/images/liminal/permaculture.jpg' },
        { name: 'Polarisation', imagePath: '/images/liminal/polarisation.png' },
        { name: 'Psychedelic Medicine', imagePath: '/images/liminal/psychedelic-medicine.png' },
        { name: 'Psychotechnology', imagePath: '/images/liminal/psychotechnology.png' },
        { name: 'Sensemaking', imagePath: '/images/liminal/sensemaking.png' },
        { name: 'Shadow Work', imagePath: '/images/liminal/shadow-work.png' },
        { name: 'Stoicism', imagePath: '/images/liminal/stoicism.jpg' },
        { name: 'Systems Change', imagePath: '/images/liminal/systems-change.png' },
        { name: 'Trauma', imagePath: '/images/liminal/trauma.png' },
        { name: 'Wisdom Cultivation', imagePath: '/images/liminal/wisdom-cultivation.png' },
    ],
}
